services:
    frontend:
        image: nginx:alpinez
        build:
            context: .
            dockerfile: frontend/Dockerfile
        ports:
            - "5000:80"
    backend:
        image: abc
        build:
            context: .
            dockerfile: backend/Dockerfile
        ports:
            - "5001:5000"