services:
    frontend:
        image: feed-me-pizza-frontend
        build:
            context: .
            dockerfile: frontend/Dockerfile
        ports:
            - "5000:80"
    backend:
        image: feed-me-pizza-backend
        build:
            context: .
            dockerfile: backend/Dockerfile
        ports:
            - "5001:5000"
    database:
        image: 'mongo'
        container_name: 'feed-me-pizza-database'
        ports:
            - '28017-28019:27017-27019'